baseURL = 'https://deus1704.vercel.app'
languageCode = 'en-in'
theme = "hello-4s3ti"
title = 'My Blog'
copyright = "All Rights Reserved"
IsMultiLingual = true
defaultContentLanguage = 'en-in'
rssURI = "rss.xml"

[outputs]
home = ["HTML", "RSS"]

[outputFormats.RSS]
baseName = "rss"
mediaType = "application/rss+xml"
protocol = "rss"
isHTML = false
notAlternative = true

[params]
  defaultTheme = "dark"
  EnableThemeToggle = true
  EnableSharingButtons = true
  EnableGlobalLanguageMenu = true
  backgroundImage = "/images/milky_way.jpg"
  backgroundEffects = true
  showPosts = true
  tags = true
  ReadMoreText = true
  fontAwesome = { KitURL = "https://kit.fontawesome.com/0ed5cec925.js" }
  ShowReadingTime = true
  LastModDisplay = true
  logo = { logoText = "Jayraj Dulange", logoCursorColor = "#4AF626" }
  footer = { showVersion = true, socialIcons = true, author = true, rss = true, trademark = true, copyright = true, bottomText = ["Powered by <a href=\"http://gohugo.io\">Hugo</a>", "with <a href=\"https://github.com/coolapso/hugo-theme-hello-4s3ti\">Hello-friend-4s3ti</a>"] }

[ params.author ]
name = "Jayraj Dulange"

[[params.social]]
  name = "github"
  url = "https://github.com/Deus1704"

[[params.social]]
  name = "x-twitter"
  url = "https://x.com/ccoolapso"

[[params.social]]
  name = "instagram"
  url = "https://www.instagram.com/c4colaco/"

[languages]
  [languages.en-in]
    weight = 1
    languageName = "English"

  [languages.en]
    weight = 2
    params = { backgroundImage = "../static/coolapso.webp" }

    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/posts"
      weight = 1

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "#"
      weight = 2

    [[languages.en.menu.main]]
      identifier = "projects"
      name = "Projects"
      url = "/projects"

    [[languages.en.menu.main]]
      identifier = "Project 1"
      name = "Project 1"
      url = "#"
      parent = "projects"

    [[languages.en.menu.main]]
      identifier = "tools"
      name = "Tools"

    [[languages.en.menu.main]]
      identifier = "tool1"
      name = "Tool 1"
      url = "#"
      parent = "tools"

    [[languages.en.menu.main]]
      identifier = "Tool2"
      name = "Tool 2"
      url = '#'
      parent = "tools"

[taxonomies]
  tag = "tags"
  category = "blog"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "#"
    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 1

  [[menu.main]]
    identifier = "tools"
    name = "Tools"

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"

  [[menu.main]]
    identifier = "Project 1"
    name = "Project 1"
    url = "#"
    parent = "projects"

  [[menu.main]]
    identifier = "Tool 1"
    name = "Tool 1"
    url = "#"
    parent = "tools"

  [[menu.main]]
    identifier = "Tool 2"
    name = "Tool 2"
    parent = "tools"
    url = "#"

  [[menu.main]]
    identifier = "Tool 3"
    name = "Tool 3"
    parent = "tools"
    url = "#"